# Generated by Django 4.1.3 on 2022-11-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('years', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salary',
            },
        ),
    ]
